package com.sonnenstahl.audioman.utils

import kotlinx.serialization.Serializable

/**
 * @brief a data class that is used to store the data of the white noises
 * generated by the user
 *
 * @property noiseType can be either White, Pink or Brown
 * @property amplitude how loud should it be
 * @property spectrum the frequency of the noise
 * @property samples the 'pace' of the noise
 */
@Serializable
data class CustomNoise(
    val noiseType: String,
    val amplitude: Float,
    val spectrum: Float,
    val samples: ByteArray,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CustomNoise

        if (amplitude != other.amplitude) return false
        if (spectrum != other.spectrum) return false
        if (noiseType != other.noiseType) return false
        if (!samples.contentEquals(other.samples)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = amplitude.hashCode()
        result = 31 * result + spectrum.hashCode()
        result = 31 * result + noiseType.hashCode()
        result = 31 * result + samples.contentHashCode()
        return result
    }
}
